

data={
    0:{#子弹
        'PATH' : 'pic/other/peabullet.png',
        'IMAGE_INDEX_MAX': 0,
        'IMAGE_INDEX_CD': 0.0,
        'POSITION_CD': 0.008,
        'SUMMON_CD':-1,
        'SIZE' : (44,44),
        'SPEED':(4,0),
        'CAN_LOOT':False,
        'PRICE':0,
    },
    1:{#僵尸
        'PATH' : 'pic/zombie/0/%d.png',
        'IMAGE_INDEX_MAX' : 15,
        'IMAGE_INDEX_CD': 0.2,
        'POSITION_CD': 0.2,
        'SUMMON_CD':-1,
        'SIZE' : (100,128),
        'SPEED':(-2.5,0),
        'CAN_LOOT':False,
        'PRICE':0,
    },
    2:{#阳光
        'PATH' : 'pic/other/sunlight/%d.png',
        'IMAGE_INDEX_MAX' : 30,
        'IMAGE_INDEX_CD': 0.02,
        'POSITION_CD': 0.05,
        'SUMMON_CD':-1,
        'SIZE' : (80,80),
        'SPEED':(0,3),
        'CAN_LOOT':True,
        'PRICE':5,
    },
    3:{#向日葵
        'PATH' : 'pic/plant/sunflower/%d.png',
        'IMAGE_INDEX_MAX' : 19,
        'IMAGE_INDEX_CD': 0.06,
        'POSITION_CD': 10000,
        'SUMMON_CD':12,
        'SIZE' : (128,128),
        'SPEED':(0,2),
        'CAN_LOOT':False,
        'PRICE':30,
    },
    4:{#豌豆射手
        'PATH' : 'pic/plant/peashooter/%d.png',
        'IMAGE_INDEX_MAX' : 15,
        'IMAGE_INDEX_CD': 0.15,
        'POSITION_CD': 10000,
        'SUMMON_CD':3,
        'SIZE' : (128,128),
        'SPEED':(0,0),
        'CAN_LOOT':False,
        'PRICE':20,
    },

}